# 如果用户没有指定 -DCMAKE_CUDA_ARCHITECTURES, 则给个默认值
if (NOT DEFINED CMAKE_CUDA_ARCHITECTURES)
    # 常用默认: 86(3080等), 87(Orin), 90(Hopper)
    set(CMAKE_CUDA_ARCHITECTURES 87 CACHE STRING "" FORCE)
endif()
message(STATUS "CMAKE_CUDA_ARCHITECTURES=${CMAKE_CUDA_ARCHITECTURES}")